apiVersion: etcd.shimo.im/v1alpha1
kind: EtcdBackup
metadata:
  name: etcd-backup
spec:
  # Add fields here
  etcdUrl: http://etcd-cluster-0.etcd-cluster.default.svc.cluster.local:2379 # 备份节点到etcd地址
  storageType: s3 # 指定备份类型
  s3:
    # path模版化 my-bucket/{{ .Namespace }}/{{ .Name }}/{{ .CreationTimestamp }}/snapshot.db
    path: "etcdbackup/{{ .Namespace }}/{{ .Name }}/{{ .UID }}/snapshot.db"  # 数据存放目录 格式：<bucket>/<object path>
    secret: "minio-access-secret"  # 包含secretID secretKey
    endpoint: "play.min.io"
  oss:
    path: "etcdbackup/etcd-snapshot.db"  # 数据存放目录 格式：<bucket>/<object path>
    secret: ""  # 包含secretID secretKey
    endpoint: "play.min.io"

# kubectl create secret generic minio-access-secret --from-literal=MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F --from-literal=MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG